### ISSUE TITLE
java.lang.NoClassDefFoundError: com/android/tools/idea/ddms/adb/AdbService

### ISSUE THREAD

**Issue by wei120698598** [bjoernQ/adc#3]
macOS   java.lang.NoClassDefFoundError: com/android/tools/idea/ddms/adb/AdbService

**Comment by bjoernQ** [comment]
I can reproduce this with Android Studio 3.1 - needs to be sorted out

**Comment by bjoernQ** [comment]
fixed in 1.0.6 (currently in review by JetBrains - should be soon available)

thanks for pointing this out
